services:
  # --- INFRAESTRUCTURA DE MENSAJERÍA ---
  redpanda:
    image: redpandadata/redpanda:latest # Versión estable 2026
    container_name: redpanda
    command: >
      redpanda start 
      --overprovisioned 
      --smp 1 
      --memory 1G 
      --reserve-memory 0M 
      --node-id 0 
      --check=false
      --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      --advertise-kafka-addr INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
      --rpc-addr 0.0.0.0:33145
      --advertise-rpc-addr redpanda:33145
    ports:
      - "9092:9092"
      - "8081:8081"
      - "9644:9644"
    networks:
      - pipeline_net
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 5s
      timeout: 5s
      retries: 10


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: redpanda-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9644
    networks:
      - pipeline_net

  # --- ALMACENAMIENTO Y VISUALIZACIÓN ---
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345
      - DOCKER_INFLUXDB_INIT_ORG=mi_org
      - DOCKER_INFLUXDB_INIT_BUCKET=finanzas
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token_secreto_2026
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - pipeline_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - pipeline_net

  # --- APLICACIÓN WEB-ENRICHMENT ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./web-enrichment-app
    container_name: rails_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./web-enrichment-app:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/rails_app_development
      KAFKA_SERVERS: redpanda:29092
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: token_secreto_2026
      INFLUX_ORG: mi_org
      INFLUX_BUCKET: finanzas
    depends_on:
      db:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    networks:
      - pipeline_net

  karafka_server:
    build: ./web-enrichment-app
    container_name: karafka_worker
    command: bundle exec karafka server
    volumes:
      - ./web-enrichment-app:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/rails_app_development
      KAFKA_SERVERS: redpanda:29092
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      web:
        condition: service_started
      redpanda:
        condition: service_healthy
    networks:
      - pipeline_net

networks:
  pipeline_net:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
  postgres_data:
  redpanda_data:
